@extends('layouts.app')

@section('content')
<div class="page-wrap">
    <header class="topbar"><div><div class="eyebrow">Operations / Access control</div><h1>Whitelist entries</h1><p class="muted">Manage approved network addresses across your application lists.</p></div><div class="topbar-meta"><span class="status-dot"></span> All systems synced</div></header>
    @if (session('status'))<div class="alert success">{{ session('status') }}</div>@endif
    <section class="stats-grid"><div class="stat-card accent"><span class="stat-label">Total entries</span><strong>{{ $total }}</strong><span class="stat-foot">Across every list</span></div><div class="stat-card"><span class="stat-label">YouTube</span><strong>{{ $ytCount }}</strong><span class="stat-foot">YT allow list</span></div><div class="stat-card"><span class="stat-label">Social networks</span><strong>{{ $snsCount }}</strong><span class="stat-foot">SNS allow list</span></div><div class="stat-card"><span class="stat-label">General ICT</span><strong>{{ $generalCount }}</strong><span class="stat-foot">General allow list</span></div></section>
    <section class="workspace-panel settings-panel"><div class="panel-heading"><div><h2>Shared allow-list destination</h2><p class="muted">One server folder is used for all users and all three generated TXT files.</p></div><span class="folder-badge">{{ auth()->user()->isSuperAdmin() ? 'ADMIN' : 'READ ONLY' }}</span></div>@if (auth()->user()->isSuperAdmin())<form method="POST" action="{{ route('admin.settings.output-directory') }}" class="directory-form">@csrf @method('PUT')<label class="directory-field {{ $errors->has('output_directory') ? 'has-error' : '' }}"><span>Full server folder path</span><input type="text" name="output_directory" value="{{ old('output_directory', $outputDirectory) }}" required maxlength="500" placeholder="C:\\laragon\\www\\EDL-lists">@error('output_directory')<span class="field-error">{{ $message }}</span>@enderror</label><button class="primary-button small" type="submit">Save shared folder <span>→</span></button></form><div class="directory-status">Files are written by the Laravel server to: <code>{{ $resolvedOutputDirectory }}</code></div>@else<div class="directory-form"><label class="directory-field"><span>Folder path</span><input type="text" value="{{ $resolvedOutputDirectory }}" readonly></label><span class="directory-readonly">Only a super admin can change this folder.</span></div>@endif</section>
    <section class="workspace-panel">
        <div class="panel-heading"><div><h2>Current access list</h2><p class="muted">Changes are written to the corresponding text files automatically.</p></div><button class="primary-button small" type="button" onclick="document.getElementById('add-entry').showModal()">Add address <span>+</span></button></div>
        <form method="GET" action="{{ route('dashboard') }}" class="filters"><label class="search-field"><span>⌕</span><input name="search" value="{{ request('search') }}" placeholder="Search name or IP address"></label><select name="application" onchange="this.form.submit()"><option value="">All applications</option><option value="YT" @selected(request('application') === 'YT')>YouTube</option><option value="FB" @selected(request('application') === 'FB')>Facebook / SNS</option><option value="BOTH" @selected(request('application') === 'BOTH')>YouTube + SNS</option><option value="GENERAL" @selected(request('application') === 'GENERAL')>General ICT</option></select><button class="ghost-button" type="submit">Filter</button></form>
        <form method="POST" action="{{ route('whitelist.bulk-destroy') }}" id="bulk-form">@csrf @method('DELETE')
            <div class="bulk-bar"><span id="selected-count">0 selected</span><button class="danger-button" type="submit" disabled id="bulk-delete" onclick="return confirm('Remove the selected whitelist entries?')">Delete selected</button></div>
            <div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="select-all"></th><th>Name</th><th>IP address</th><th>Application</th><th>Added by</th><th>Request IP</th><th>Updated</th><th></th></tr></thead><tbody>
                @forelse ($entries as $entry)<tr><td><input type="checkbox" name="entry_ids[]" value="{{ $entry->id }}" class="entry-check"></td><td><strong>{{ $entry->name }}</strong></td><td><code>{{ $entry->ip_address }}</code></td><td><span class="tag tag-{{ strtolower($entry->application) }}">{{ $entry->application === 'BOTH' ? 'YT + SNS' : ($entry->application === 'GENERAL' ? 'General ICT' : $entry->application) }}</span></td><td><strong>{{ $entry->creator?->name ?: 'Unknown' }}</strong><small class="cell-note">{{ $entry->creator?->email }}</small></td><td><code>{{ $entry->added_ip_address ?: '—' }}</code></td><td class="muted">{{ $entry->updated_at->diffForHumans() }}</td><td class="actions"><a href="{{ route('whitelist.edit', $entry) }}" title="Edit entry">Edit</a><button type="submit" form="delete-{{ $entry->id }}" title="Remove entry">×</button></td></tr>@empty<tr><td colspan="8" class="empty-state">No whitelist entries yet. Add the first approved address.</td></tr>@endforelse
            </tbody></table></div>
        </form>
        @foreach ($entries as $entry)<form method="POST" action="{{ route('whitelist.destroy', $entry) }}" id="delete-{{ $entry->id }}">@csrf @method('DELETE')</form>@endforeach
        @if ($entries->hasPages())<div class="pagination">{{ $entries->links() }}</div>@endif
    </section>
</div>
<dialog id="add-entry"><form method="POST" action="{{ route('whitelist.store') }}" class="modal-card">@csrf<div class="modal-heading"><div><div class="eyebrow">New entry</div><h2>Add approved address</h2></div><button type="button" class="close-button" onclick="this.closest('dialog').close()">×</button></div>@include('entries.form', ['entry' => null])<div class="modal-actions"><button type="button" class="ghost-button" onclick="this.closest('dialog').close()">Cancel</button><button class="primary-button" type="submit">Save address <span>→</span></button></div></form></dialog>
<script>const checks=[...document.querySelectorAll('.entry-check')],all=document.getElementById('select-all'),button=document.getElementById('bulk-delete'),count=document.getElementById('selected-count');function updateSelection(){const n=checks.filter(c=>c.checked).length;count.textContent=n+' selected';button.disabled=!n;all.checked=n===checks.length&&n>0;}checks.forEach(c=>c.addEventListener('change',updateSelection));all?.addEventListener('change',()=>{checks.forEach(c=>c.checked=all.checked);updateSelection()});</script>
@endsection
